### ISSUE TITLE
Continuing examples

### ISSUE THREAD

**Issue by TiemenSch** [pydantic/pytest-examples#13]
Would you consider supporting "continuing" examples that a feature text in between code fences? 

For example:

```python
foo = "bar"
```

We set `foo` to `"bar"` to indicate bar. We can then print `"Quux!"`

```python
if foo == "bar":
    print("Quux!")
#> "Quux!"
```

Currently, I'm trying some sort of hybrid setup with [pytest-markdown-docs](https://github.com/modal-labs/pytest-markdown-docs) that supports it, but that more or less has to run every example twice. Also their ` ```python continuation ` thing doesn't quite render right in MkDocs.

**Comment by TiemenSch** [comment]
This might make the formatters and linters quite sad, though.

**Comment by samuelcolvin** [comment]
Happy to accept a change to fix this if it's not too complicated. How would you implement a fix?

**Comment by rmorshea** [comment]
For reference I'm [already using this strategy](https://github.com/rmorshea/pybooster/blob/f6a80c19cd261ee404f56e042be1fd9af5f98ad1/tests/test_docs.py#L20) to skip testing certain docstrings by marking them with `{ test="false" }`.

**Comment by samuelcolvin** [comment]
you can do this pretty well by registering examples in `sys.modules` before running other examples, then importing the previous example.

You can also pass `module_globals` if you don't want the imports. So I think this is working as expected.
