### ISSUE TITLE
0.0.10: Tests missing in sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [pydantic/pytest-examples#16]
Hi! I'm packaging this project for Arch Linux.
When trying to run tests I realized that the sdist tarball on pypi.org does not offer any tests.

Could you include them with the next version? :)

A lot of downstreams still rely on sdist tarballs (for various reasons).

**Comment by samuelcolvin** [comment]
Sorry, our mistake.

Pr welcome to fix this.
